### ISSUE TITLE
Support for image board sites like gelbooru,danbooru,konachan,chan.sankakucomplex.com etc..

### ISSUE THREAD

**Issue by YukiSakuma** [eiurur/Save-to-Kawpaa#4]
thanks

**Comment by eiurur** [comment]
### gelbooru

![chrome_2016-03-14_01-14-13](https://cloud.githubusercontent.com/assets/4101830/13730640/ce250d00-e997-11e5-84ed-4b0b79f44a15.png)

### danbooru

![chrome_2016-03-14_03-34-09](https://cloud.githubusercontent.com/assets/4101830/13730638/c6788d8e-e997-11e5-8787-c8d214f5fdd8.png)

### konachan

![chrome_2016-03-14_01-30-30](https://cloud.githubusercontent.com/assets/4101830/13730642/e0804866-e997-11e5-8dcc-55650f3e3aa8.png)

### chan.sankakucomplex.com

![chrome_2016-03-14_03-51-02](https://cloud.githubusercontent.com/assets/4101830/13730649/0100705c-e998-11e5-91ab-173f4d405c7a.png)

### yande.re

![chrome_2016-03-14_01-36-30](https://cloud.githubusercontent.com/assets/4101830/13730651/0687c9f8-e998-11e5-8a3f-5fe109b4d963.png)

## Result

![chrome_2016-03-14_03-58-55](https://cloud.githubusercontent.com/assets/4101830/13730688/1ca34798-e999-11e5-8f9b-d0a6842f049b.jpg)

**Comment by eiurur** [comment]
supported from v0.7.0. Thank you.

**Comment by YukiSakuma** [comment]
Thank you so much for the add on but I have another request if you may, pixiv and deviantart

**Comment by seiffchi** [comment]
May you add for [anime-pictures(net)] and [nozomi(la)] too?

**Comment by eiurur** [comment]
Thank you for request.  Supported from v0.13.0.

# Example

### anime-picutres.net

![chrome_2019-03-11_01-18-53](https://user-images.githubusercontent.com/4101830/54088011-7ea1c180-439c-11e9-8b41-4040be4e0a68.png)

> https://anime-pictures.net/pictures/view_post/589559?lang=jp

### nozomi.la

![chrome_2019-03-11_01-19-06](https://user-images.githubusercontent.com/4101830/54088009-75185980-439c-11e9-95c2-fa1bf9a51daf.jpg)

> https://nozomi.la/post/7384683.html#hatsune_miku

## result

![chrome_2019-03-11_01-19-58](https://user-images.githubusercontent.com/4101830/54088006-7184d280-439c-11e9-8a02-fe151e94b667.png)
